/**:
  ros__parameters:
    system:
      performance_mode: False
    nmpc_config:
      ref_velocity: 3.0             # 期望巡航速度 (m/s)
      control_loop_ms: 50           # 控制循环周期 (毫秒)
      enable_warm_start: False
      curvature_threshold: 2.0
      global_curvature_weight: 1.0

    safety:
      max_cte_ratio: 100000.0     #暂时不开
      recovery_velocity: 0.5

    track:
      road_half_width: 7.0
      use_virtual_walls: False

    perception:
      dbscan_eps: 1.2               # DBSCAN 邻域搜索半径
      dbscan_min_pts: 3             # 形成簇所需的最小点数
      fov_half_angle_deg: 100.0     # 机器人前方视野半角 (度)

    obstacle_avoidance:
      base_margin: 1.5              # 基础安全距离/机器人半径 (米)

    robot_limits:
      max_linear_velocity: 5.1      # 最大线速度限制 (m/s)
      min_linear_velocity: 0.0      # 最小线速度限制 (m/s)
      max_angular_velocity: 2.0     # 最大角速度限制 (rad/s)
      min_angular_velocity: -2.0    # 最小角速度限制 (rad/s)

    eso:
      enable: True
      omega_linear: 5.0
      omega_angular: 1.0
      b0_linear: 1.0
      b0_angular: 1.0
      
    sfc:
      enable: False
      robot_radius: 1.0
      search_radius: 5.0
      longitudinal_length: 4.0
      
    lattice:
      path_resolution: 0.2
      lookahead_dist: 30.0
      num_samples: 500
      sample_width: 0.1
      max_width: 50.0
      collision_radius: 1.0
      weight_collision: 1000.0
      weight_offset: 1.0
      weight_consistency: 4.0

    quintic:
      weight_lat: 0.2
      weight_collision: 1000.0
      weight_lon: 1.0
      weight_jerk: 0.1
      num_samples: 30
      sample_width: 0.4
      min_lookahead: 2.0
      max_lookahead: 5.0
      max_lat_sample: 10.0
      collision_radius: 0.8
