/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) racing_control_hyperplane_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {5, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {25, 1, 1};
static const casadi_int casadi_s4[18] = 
  {7, 5, 0, 2, 4, 6, 8, 10,
  2, 3, 2, 3, 2, 3, 2, 3,
  2, 3};
static const casadi_int casadi_s5[3] = {5, 0, 1};

/* racing_control_hyperplane_constr_h_fun_jac_uxt_zt:(i0[5],i1[2],i2[0],i3[25])->(o0[5],o1[7x5,10nz],o2[5x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12;
  a00=arg[3]? arg[3][3] : 0;
  a01=arg[0]? arg[0][0] : 0;
  a02=arg[3]? arg[3][0] : 0;
  a02=(a01-a02);
  a02=(a00*a02);
  a03=arg[3]? arg[3][4] : 0;
  a04=arg[0]? arg[0][1] : 0;
  a05=arg[3]? arg[3][1] : 0;
  a05=(a04-a05);
  a05=(a03*a05);
  a02=(a02+a05);
  a05=arg[3]? arg[3][2] : 0;
  a02=(a02-a05);
  if (res[0]!=0) res[0][0]=a02;
  a02=arg[3]? arg[3][8] : 0;
  a05=arg[3]? arg[3][5] : 0;
  a05=(a01-a05);
  a05=(a02*a05);
  a06=arg[3]? arg[3][9] : 0;
  a07=arg[3]? arg[3][6] : 0;
  a07=(a04-a07);
  a07=(a06*a07);
  a05=(a05+a07);
  a07=arg[3]? arg[3][7] : 0;
  a05=(a05-a07);
  if (res[0]!=0) res[0][1]=a05;
  a05=arg[3]? arg[3][13] : 0;
  a07=arg[3]? arg[3][10] : 0;
  a07=(a01-a07);
  a07=(a05*a07);
  a08=arg[3]? arg[3][14] : 0;
  a09=arg[3]? arg[3][11] : 0;
  a09=(a04-a09);
  a09=(a08*a09);
  a07=(a07+a09);
  a09=arg[3]? arg[3][12] : 0;
  a07=(a07-a09);
  if (res[0]!=0) res[0][2]=a07;
  a07=arg[3]? arg[3][18] : 0;
  a09=arg[3]? arg[3][15] : 0;
  a09=(a01-a09);
  a09=(a07*a09);
  a10=arg[3]? arg[3][19] : 0;
  a11=arg[3]? arg[3][16] : 0;
  a11=(a04-a11);
  a11=(a10*a11);
  a09=(a09+a11);
  a11=arg[3]? arg[3][17] : 0;
  a09=(a09-a11);
  if (res[0]!=0) res[0][3]=a09;
  a09=arg[3]? arg[3][23] : 0;
  a11=arg[3]? arg[3][20] : 0;
  a01=(a01-a11);
  a01=(a09*a01);
  a11=arg[3]? arg[3][24] : 0;
  a12=arg[3]? arg[3][21] : 0;
  a04=(a04-a12);
  a04=(a11*a04);
  a01=(a01+a04);
  a04=arg[3]? arg[3][22] : 0;
  a01=(a01-a04);
  if (res[0]!=0) res[0][4]=a01;
  if (res[1]!=0) res[1][0]=a00;
  if (res[1]!=0) res[1][1]=a03;
  if (res[1]!=0) res[1][2]=a02;
  if (res[1]!=0) res[1][3]=a06;
  if (res[1]!=0) res[1][4]=a05;
  if (res[1]!=0) res[1][5]=a08;
  if (res[1]!=0) res[1][6]=a07;
  if (res[1]!=0) res[1][7]=a10;
  if (res[1]!=0) res[1][8]=a09;
  if (res[1]!=0) res[1][9]=a11;
  return 0;
}

CASADI_SYMBOL_EXPORT int racing_control_hyperplane_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int racing_control_hyperplane_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int racing_control_hyperplane_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void racing_control_hyperplane_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int racing_control_hyperplane_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void racing_control_hyperplane_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void racing_control_hyperplane_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void racing_control_hyperplane_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int racing_control_hyperplane_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int racing_control_hyperplane_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real racing_control_hyperplane_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* racing_control_hyperplane_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* racing_control_hyperplane_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* racing_control_hyperplane_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* racing_control_hyperplane_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int racing_control_hyperplane_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int racing_control_hyperplane_constr_h_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
